Repository MemePlace/Server, pull requests merged in 2018-04, with the labels that each got.

#33 Adds Template API Endpoints
  README.md
  models/Template.js
  routes/api/templates/index.js
  routes/api/v1.js
Labels: enhancement

#34 Adds Endpoint for Fetching Community Templates and Fixes Sorting Retrieval
  README.md
  routes/api/communities/index.js
  routes/api/templates/index.js
  routes/api/utils.js
Labels: bug, enhancement

#36 Fixes CORS Allow Headers
  index.js
Labels: bug

#35 Meme API
  models/CommentVote.js
  models/Meme.js
  models/MemeVote.js
  package-lock.json
  routes/api/memes/index.js
  routes/api/utils.js
  routes/api/v1.js
Labels: enhancement

#38 Adds Explicit CORS Allowed Methods
  index.js
Labels: bug

#39 Adds Access Control Allow Credentials to Server Response
  index.js
Labels: bug

#42 Adds Meme API Endpoints to Readme
  README.md
Labels: enhancement

#49 Adds Image DB Model to Store Images and Their Dimensions
  README.md
  models/Image.js
  models/Meme.js
  models/Template.js
  routes/api/memes/index.js
  routes/api/templates/index.js
  routes/api/utils.js
Labels: enhancement

#47 Changes Meme Vote Dupe Error status to 400
  routes/api/memes/index.js
Labels: bug

#55 Adds Meme Retrieval for Communities and Refactors
  models/MemeVote.js
  routes/api/communities/index.js
  routes/api/memes/index.js
  routes/api/utils.js
Labels: enhancement

#58 Adds Hot Sorting Algorithm for Memes
  models/Meme.js
  models/MemeVote.js
  routes/api/communities/index.js
  routes/api/memes/index.js
  routes/api/utils.js
  utils.js
Labels: enhancement

#60 Merges Hot Algo #58 to Master
  models/Meme.js
  models/MemeVote.js
  routes/api/communities/index.js
  routes/api/memes/index.js
  routes/api/utils.js
  utils.js
Labels: enhancement

#64 Persists User Sessions in Sequelize DB
  index.js
  package-lock.json
  package.json
Labels: enhancement

#63 Adds Meme Votes for User in Meme List API Methods
  models/Meme.js
  routes/api/communities/index.js
  routes/api/memes/index.js
  routes/api/utils.js
Labels: bug, enhancement

#66 Adds HTTPS Cert Support
  .gitignore
  config.example.js
  index.js
Labels: enhancement
